#!/bin/bash

# test if pre-reqs are intalled

command -v youtube-dl > /dev/null

if [ $? == 1 ]
then
    echo "youtube-dl is not installed. Try installing using apt, yum, nala, etc.."
    exit 1
fi

command -v ffmpeg > /dev/null

if [ $? == 1 ]
then
    echo "ffmpeg is not installed. Try installing using apt, yum, nala, etc.."
    exit 1
fi


if [ $# -lt 1 ]
then
    echo "yt-clipper needs an url as an argument"
    exit 1
fi

st=-1 # when to start recording
nd=-1 # when to end recording

outputName=output.mkv

while test $# -gt 0; do
    case "$1" in
	-h) echo "usage:"
	    echo "    yt-clipper <youtube video url> [options]"
	    echo ;
	    echo "Options"
	    echo " -h display this message"
	    echo ; 
	    echo " -o output file name (include extension)"
	    echo ;
	    echo " -s when to start clipping the video"
	    echo "    use HH:MM:SS.S format"
	    echo ; 
	    echo " -e When to stop clipping the video"
	    echo "    use HH:MM:SS.S format"
	    echo ;
	    echo "Example"
	    echo "    yt-clipper https://youtu.be/aSk-D86aOtc -o oceanWaves.mkv -e 00:00:45.0"
	    echo ; 
	    exit 0;;
	-o) shift   # output file name
	    outputName="$1"
	    shift;;
	-s) shift
	    st="$1"
	    shift;;
	-e) shift
	    nd="$1"
	    shift;;
	*) url=$(youtube-dl -g $1)
	   shift;; 
    esac
done 

arr=(${url//[ ]/})



video=${arr[0]}
audio=${arr[1]}

if [[ $st != -1 ]] && [[ $en != -1 ]]
then
    ffmpeg -ss $st -t $nd  -i $video -ss $st -t $nd -i $audio -map 0:v -map 1:a -c:v copy -c:a copy $outputName
    
elif [[ $st == -1 ]] && [[ $en != -1 ]]
then
    ffmpeg -t $nd  -i $video -t $nd -i $audio -map 0:v -map 1:a -c:v copy -c:a copy $outputName
    
elif [[ $st == -1 ]] && [[ $en == -1 ]]
then
    ffmpeg -i $video -i $audio -map 0:v -map 1:a -c:v copy -c:a copy $outputName
    
fi


